# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

if [[ -z $PS1 ]]; then return; fi
if [[ -n $IN_NIX_SHELL ]]; then return; fi

if [[ ! -d ~/.temp ]]; then mkdir ~/.temp; fi

shopt -s histappend
# https://stackoverflow.com/a/19533853/199134
# Eternal bash history.
# ---------------------
# Undocumented feature which sets the size to "unlimited".
# http://stackoverflow.com/questions/9457233/unlimited-bash-history
export HISTFILESIZE=
export HISTSIZE=
export HISTTIMEFORMAT="[%F %T] "
# Change the file location because certain bash sessions truncate .bash_history file upon close.
# http://superuser.com/questions/575479/bash-history-truncated-to-500-lines-on-each-login
export HISTFILE=~/.bash_global_history
# Force prompt to write history after every command.
# http://superuser.com/questions/20900/bash-history-loss
PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

export TERM=xterm

function Zalias_cmd {
  old=$1
  new=$2
  # If the old command is found, make an upper-case alias to it
  location=$(command -v $old)
  if [ -x "$location" ]; then
    alias ${old^^}=$location
  fi
  # Alias the command
  alias $old=$new
}

# 'Modern' Unix commands, aliased over originals:
Zalias_cmd cat bat
Zalias_cmd du dust
Zalias_cmd find fd
Zalias_cmd grep rg
Zalias_cmd htop btm
Zalias_cmd ls exa
Zalias_cmd man tldr
Zalias_cmd sed sd
Zalias_cmd tree br
Zalias_cmd ps procs

# Helpful aliases
alias ll='exa -l'
alias lt='exa -l -tmodified -snew'
alias la='exa -la'
alias lsmod='stat -f "%Mp%Lp %N"'
alias df='df -h'
alias rsync='rsync --progress'
alias bc='bc -l'

# https://www.atlassian.com/git/tutorials/dotfiles
alias config='git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
#config config --local status.showUntrackedFiles no

# stty intr ^k
# Disable XON/XOFF ctrl-s freeze, ctrl-q resume:
stty -ixon

# Rust toolchain
source $HOME/.cargo/env

function Zgit_parse_branch {
  git branch 2>> /dev/null 2>&1 | SED -e '/^[^*]/d' -e 's/* \(.*\)/\1/'
}
export PS1="\[\e[32m\]\u\[\e[39m\]@\[\e[34m\]\h\[\e[39m\] \[\e[33m\]\W\[\e[0m\] \[\e[36m\]\$(Zgit_parse_branch)\[\e[00m\] \[\e[37m\]\D{%F %T}\[\e[39m\]\n\$ "

# https://github.com/junegunn/fzf
export FZF_DEFAULT_COMMAND="rg --color auto --files"
if command -v fzf-share >/dev/null; then
  source "$(fzf-share)/key-bindings.bash"
  source "$(fzf-share)/completion.bash"
fi

# bash-completion:
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi
for bcfile in ~/.nix-profile/etc/bash_completion.d/* ; do
  . $bcfile
done

function Zshow_tips {
  ARG="$1"
  TODAY=$(date -I)
  if [ -e ~/.homies_tips ]; then
    source ~/.homies_tips
  fi
  if [ "$ARG" == "" ] || [ ! "$TODAY" == "$LASTMSG" ]; then
    echo "LASTMSG=$TODAY" > ~/.homies_tips
    echo "Extra utils: bat, dust, exa, fzf, fd, sd, rg, jq, br, tldr, hyperfine, btm, procs, xh"
  fi
}

Zshow_tips daily

# Set up direnv
eval "$(direnv hook bash)"
